"""Initial migration

Revision ID: e15f1fd504f4
Revises: 7b0cb4e5b351
Create Date: 2024-12-11 15:03:21.951994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e15f1fd504f4'
down_revision: Union[str, None] = '7b0cb4e5b351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
